### ISSUE TITLE
Preserve current mapview when switching styles or webview api

### ISSUE THREAD

**Issue by clkao** [klokantech/tileserver-mapnik#18]

**Comment by klokan** [comment]
Thanks for the ticket. It is rather unclear what you want to make - and there is no description for the ticket at all.

It seems you speak about the web client implementation. This repo is for the server software.
If you make and use the server with your own web client you can preserve location while switching tiles with different styles easily - use Leaflet, OpenLayers, Google Maps, etc.

It is also unclear what the mentioned "webview api" means in this context. Closing.

BTW It is recommended to use tileserver-gl instead of tileserver-mapnik with the recent OSM2VectorTiles.

**Comment by clkao** [comment]
Hi sorry for the confusion.  This is about the [docker image](https://hub.docker.com/r/klokantech/tileserver-mapnik/) apparently built from this repo.

By following the instructions here: http://osm2vectortiles.org/docs/serve-raster-tiles-docker/, one gets "Maps rendered by Mapnik from vector tiles" demo page which allows switching between different frontend apis.  What I meant is that the map view should persist when switching to different api.
